server:
  port: 8189
  servlet:
    context-path: /rest

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test
#    localhost:8189/rest/h2
#    JDBC URL: jdbc:h2:mem:~/test
#    username: sa
#    password:

